[project]
name = "ml-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "catboost>=1.2.10",
    "ipython>=9.15.0",
    "joblib>=1.5.3",
    "jupytext>=1.19.4",
    "lightgbm>=4.6.0",
    "lxml>=6.1.1",
    "marimo>=0.23.3",
    "matplotlib>=3.10.9",
    "nbformat>=5.10.4",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "scikit-learn>=1.9.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "tabulate>=0.10.0",
    "xgboost>=3.3.0",
]

[tool.jupytext]
formats = "ipynb,py:marimo"
